# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/advaywelling/Purdue/CS files/Algo Trading"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/advaywelling/Purdue/CS files/Algo Trading"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/advaywelling/Purdue/CS files/Algo Trading/CMakeFiles" "/Users/advaywelling/Purdue/CS files/Algo Trading//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/advaywelling/Purdue/CS files/Algo Trading/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named market_data

# Build rule for target.
market_data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 market_data
.PHONY : market_data

# fast build rule for target.
market_data/fast:
	$(MAKE) $(MAKESILENT) -f market_data/CMakeFiles/market_data.dir/build.make market_data/CMakeFiles/market_data.dir/build
.PHONY : market_data/fast

#=============================================================================
# Target rules for targets named strategy_engine

# Build rule for target.
strategy_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 strategy_engine
.PHONY : strategy_engine

# fast build rule for target.
strategy_engine/fast:
	$(MAKE) $(MAKESILENT) -f strategy_engine/CMakeFiles/strategy_engine.dir/build.make strategy_engine/CMakeFiles/strategy_engine.dir/build
.PHONY : strategy_engine/fast

#=============================================================================
# Target rules for targets named order_management

# Build rule for target.
order_management: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 order_management
.PHONY : order_management

# fast build rule for target.
order_management/fast:
	$(MAKE) $(MAKESILENT) -f order_management/CMakeFiles/order_management.dir/build.make order_management/CMakeFiles/order_management.dir/build
.PHONY : order_management/fast

#=============================================================================
# Target rules for targets named execution_engine

# Build rule for target.
execution_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 execution_engine
.PHONY : execution_engine

# fast build rule for target.
execution_engine/fast:
	$(MAKE) $(MAKESILENT) -f execution_engine/CMakeFiles/execution_engine.dir/build.make execution_engine/CMakeFiles/execution_engine.dir/build
.PHONY : execution_engine/fast

#=============================================================================
# Target rules for targets named risk_management

# Build rule for target.
risk_management: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 risk_management
.PHONY : risk_management

# fast build rule for target.
risk_management/fast:
	$(MAKE) $(MAKESILENT) -f risk_management/CMakeFiles/risk_management.dir/build.make risk_management/CMakeFiles/risk_management.dir/build
.PHONY : risk_management/fast

#=============================================================================
# Target rules for targets named latency_monitoring

# Build rule for target.
latency_monitoring: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 latency_monitoring
.PHONY : latency_monitoring

# fast build rule for target.
latency_monitoring/fast:
	$(MAKE) $(MAKESILENT) -f latency_monitoring/CMakeFiles/latency_monitoring.dir/build.make latency_monitoring/CMakeFiles/latency_monitoring.dir/build
.PHONY : latency_monitoring/fast

#=============================================================================
# Target rules for targets named algo_trading_app

# Build rule for target.
algo_trading_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 algo_trading_app
.PHONY : algo_trading_app

# fast build rule for target.
algo_trading_app/fast:
	$(MAKE) $(MAKESILENT) -f app/CMakeFiles/algo_trading_app.dir/build.make app/CMakeFiles/algo_trading_app.dir/build
.PHONY : algo_trading_app/fast

#=============================================================================
# Target rules for targets named test_market_data

# Build rule for target.
test_market_data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_market_data
.PHONY : test_market_data

# fast build rule for target.
test_market_data/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_market_data.dir/build.make tests/CMakeFiles/test_market_data.dir/build
.PHONY : test_market_data/fast

#=============================================================================
# Target rules for targets named test_strategy_engine

# Build rule for target.
test_strategy_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_strategy_engine
.PHONY : test_strategy_engine

# fast build rule for target.
test_strategy_engine/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_strategy_engine.dir/build.make tests/CMakeFiles/test_strategy_engine.dir/build
.PHONY : test_strategy_engine/fast

#=============================================================================
# Target rules for targets named test_order_management

# Build rule for target.
test_order_management: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_order_management
.PHONY : test_order_management

# fast build rule for target.
test_order_management/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_order_management.dir/build.make tests/CMakeFiles/test_order_management.dir/build
.PHONY : test_order_management/fast

#=============================================================================
# Target rules for targets named test_execution_engine

# Build rule for target.
test_execution_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_execution_engine
.PHONY : test_execution_engine

# fast build rule for target.
test_execution_engine/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_execution_engine.dir/build.make tests/CMakeFiles/test_execution_engine.dir/build
.PHONY : test_execution_engine/fast

#=============================================================================
# Target rules for targets named test_risk_management

# Build rule for target.
test_risk_management: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_risk_management
.PHONY : test_risk_management

# fast build rule for target.
test_risk_management/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_risk_management.dir/build.make tests/CMakeFiles/test_risk_management.dir/build
.PHONY : test_risk_management/fast

#=============================================================================
# Target rules for targets named test_latency_monitoring

# Build rule for target.
test_latency_monitoring: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_latency_monitoring
.PHONY : test_latency_monitoring

# fast build rule for target.
test_latency_monitoring/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_latency_monitoring.dir/build.make tests/CMakeFiles/test_latency_monitoring.dir/build
.PHONY : test_latency_monitoring/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... algo_trading_app"
	@echo "... execution_engine"
	@echo "... latency_monitoring"
	@echo "... market_data"
	@echo "... order_management"
	@echo "... risk_management"
	@echo "... strategy_engine"
	@echo "... test_execution_engine"
	@echo "... test_latency_monitoring"
	@echo "... test_market_data"
	@echo "... test_order_management"
	@echo "... test_risk_management"
	@echo "... test_strategy_engine"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

