if(EXISTS "/Users/advaywelling/Purdue/CS files/Algo Trading/tests/test_execution_engine[1]_tests.cmake")
  include("/Users/advaywelling/Purdue/CS files/Algo Trading/tests/test_execution_engine[1]_tests.cmake")
else()
  add_test(test_execution_engine_NOT_BUILT test_execution_engine_NOT_BUILT)
endif()
